# Generated by Django 3.0 on 2022-10-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description_short', models.CharField(max_length=250, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Coordinates', verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='places.Feature', verbose_name='Набор изображений')),
                ('images', models.ManyToManyField(to='places.Image')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='places.FeatureImageSet'),
        ),
    ]
