# Generated by Django 3.0 on 2022-10-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image_set',
        ),
        migrations.DeleteModel(
            name='FeatureImageSet',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
