# Generated by Django 3.0 on 2022-10-14 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20221014_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Feature', verbose_name='Координаты'),
        ),
    ]
