# Generated by Django 3.2.15 on 2022-12-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20221014_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/palaces', verbose_name='Фото места')),
                ('alt', models.CharField(max_length=150, verbose_name='Alt изображения')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='places.feature')),
            ],
            options={
                'verbose_name': 'Фото места',
                'verbose_name_plural': 'Фото мест',
            },
        ),
    ]
