# Generated by Django 3.2.15 on 2022-12-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20221206_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureimage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='feature',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='places.feature'),
        ),
    ]
