# Generated by Django 3.2.15 on 2022-12-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20221206_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureimage',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='places.feature'),
        ),
    ]
