# Generated by Django 3.2.15 on 2022-12-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_featureimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureimage',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.feature'),
        ),
    ]
