# Generated by Django 4.1.4 on 2022-12-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_featureimage_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['title'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='featureimage',
            options={'ordering': ['order'], 'verbose_name': 'Фото места', 'verbose_name_plural': 'Фото мест'},
        ),
    ]
