# Generated by Django 4.1.4 on 2022-12-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_feature_options_alter_feature_description_long_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureImage',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Feature',
            new_name='Place',
        ),
    ]
