# Generated by Django 4.1.4 on 2022-12-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_place_lat_alter_place_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt',
        ),
    ]
