# Generated by Django 4.1.4 on 2022-12-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_remove_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='feature',
            new_name='place',
        ),
    ]
